before:
  hooks:
    - go mod tidy
project_name: athena
builds:
  - main: athena.go
    binary: athena
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    format: tar.gz
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - config_sample/*
