[Server]
# The address to listen on. Leave blank to listen on any. If you don't know what you're doing, leave this blank.
addr = ""

# The port to listen for connections on.
port = 27016

# Whether to listen for websocket (WebAO) connections.
enable_webao = false

# The port to listen for websocket (WebAO) connections on.
webao_port = 27017

# The name of your server. This is used both on the server list, and within the server.
name = "Unnamed Server"

# The description of your server.
description = "A brand new server!"

# The maximum amount of players who can join the server at once.
max_players = 100

# The maximum amount of bytes that players can send in a message. Long messages can slow down clients, 
# so don't make this too large.
max_message_length = 256

# Sets the detault length of bans.
# This must be a number followed by a unit. Example: "3w" - three weeks.
# Valid units are "s" (second), "m" (minute), "h" (hour), "d" (day), "w" (week).
default_ban_duration = "3d"

# Sets the number of actions (IC chat messages, OOC chat messages, judge actions, etc.) each area should store.
# When a user calls a mod, this buffer will be flushed to a report file for review.
log_buffer_size = 150

# Sets the log level. Events of lower levels will not be logged.
# Valid levels: debug, info, warning, error, fatal
log_level = "info"

# Sets the path to the log directory.
# This directory will be used for storing report files and the server audit log.
log_directory = "logs"

[MasterServer]

# Whether or not to advertise your server on the master server, which will make it discoverable by players.
# If you want to keep your server private, set this as false.
advertise = false

# The address of the master server. You shouldn't change this unless you know what you're doing.
addr = "https://servers.aceattorneyonline.com/servers"
