[Server]
# The address to listen on. Leave blank to listen on any. If you don't know what you're doing, leave this blank.
addr = ""

# The port to listen for connections on.
port = 27016

# Whether to listen for websocket (WebAO) connections.
enable_webao = false

# The port to listen for websocket (WebAO) connections on.
webao_port = 27017

# The name of your server. This is used both on the server list, and within the server.
name = "Unnamed Server"

# The description of your server.
description = "A brand new server!"

# Sets the server's message of the day (MoTD)
# This is sent to every player when they first join the server, or with /motd.
motd = "Welcome to my server!"

# The maximum amount of players who can join the server at once.
max_players = 100

# The maximum amount of bytes that players can send in a message. Long messages can slow down clients, 
# so don't make this too large.
max_message_length = 256

# Sets the detault length of bans.
# This must be a number followed by a unit. Example: "3w" - three weeks.
# Valid units are "s" (second), "m" (minute), "h" (hour), "d" (day), "w" (week).
default_ban_duration = "3d"

# Sets the number of client connections that can be made from the same IP, also known as "multiclienting".
# Set to 0 to disable multiclient limiting.
multiclient_limit = 16

# Sets the URL for the server's WebAO assets.
# If this is blank, vanilla assets will be used.
asset_url = ""

# Sets the URL for the server's Discord webhook.
# If this is blank, the discord webhook will be disabled.
# To setup the webhook, follow the instructions here (https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks)
# and set this to the URL of your webhook.
webhook_url = ""

# Sets the maximum number of dice that can be rolled at once.
max_dice = 100

# Sets the maximum number of sides a rolled dice can have.
max_side = 100

# Sets the maximum number of statements a recorded testimony can contain.
max_testimony = 10

[Logging]
# Sets the number of actions (IC chat messages, OOC chat messages, judge actions, etc.) each area should store.
# When a user calls a mod, this buffer will be flushed to a report file for review.
log_buffer_size = 150

# Sets the log level. Events of lower levels will not be logged.
# Valid levels: debug, info, warning, error, fatal
log_level = "info"

# Sets the path to the log directory.
# This directory will be used for storing report files, the server audit log, and the server log.
log_directory = "logs"

# Sets whether to log to stdout.
# If set to true, will write logs to the CLI.
log_stdout = true

# Sets whether to log to a file.
# If set to true, will write logs to server.log in log_directory.
log_file = false

[MasterServer]

# Whether or not to advertise your server on the master server, which will make it discoverable by players.
# If you want to keep your server private, set this as false.
advertise = false

# The address of the master server. You shouldn't change this unless you know what you're doing.
addr = "https://servers.aceattorneyonline.com/servers"
